### PR TITLE
Disable Style/GuardClause and release 1.2.0

### PR DESCRIPTION
**Pull request by tas50**
GuardClause results in some awful code to read for new users. Instead of having simple if/else logic you end up with returns that break simple logic flows. It's not an improvement.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by lamont-granquist** [comment]
might want to include an example of where it produces crappier code.

generally i prefer this style over the thou-shalt-never-return-early style of coding, and find it more readable.   the major problem with thou-shalt-not-return-early is that you can skip cleanup at the end of the method, but `ensure` is the proper tool to use to fix that.

**Comment by tas50** [comment]
I can live with this one even though I think it makes for harder to read code for beginners

**Comment by lamont-granquist** [comment]
i've been playing around with this one and still don't see where it produces crappy code, and i've been submitting some code that is fixed for it to chef/chef and haven't been seeing any issues...

its possible that there's patterns of how to fix it which are awful, but so far all the fixes i've done look entirely readable to my eye...

**Comment by lamont-granquist** [comment]
yeah we should disable GuardClause, it is bad.

**Comment by iennae** [comment]
replaced with PR #42.

**Pull request closed without merging**
