### PR TITLE
Update to Rubocop 0.42 and exclude regex rules in test/**/*

### PR DESCRIPTION
**Pull request by tas50**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
0.42 failed pretty badly in my testing chefstyle on chef/chef

https://github.com/chef/chefstyle/issues/29

**Comment by lamont-granquist** [comment]
@tas50 nevermind, 0.42.0 looks okay -- i think its just the chefstyle ruleset which needs fixing to avoid the infinite loop i was seeing with it.

**Comment by lamont-granquist** [comment]
note that upgrading to 0.42.0 with the same ruleset changes the behavior of a few specs, which will catch some offenses that were previously (erroneously) ignored -- so it might still cause some cookbooks to fail.

**Comment by tas50** [comment]
Closing this in favor of a bump to 0.46

**Pull request closed without merging**
