### PR TITLE
bump rubocop engine to 0.41.1

### PR DESCRIPTION
**Pull request by lamont-granquist**
does not change cookstyle definitions.   all new cops disabled.  validated on activemq, aws, build-essential, docker, nscd, and the results match with prior release of cookstyle.

### CODE REVIEW

**Comment by lamont-granquist** [comment]
all of the code changes here are autogenerated from 'rake vendor'

**Comment by lamont-granquist** [comment]
travis has always been broken, dating back to the first commit to chefstyle, and i didn't sign up for shaving that yak today...

**Comment by tas50** [comment]
Ship it

**Comment by thommay** [comment]
:shipit:

**Comment by lamont-granquist** [comment]
turns out this version of rubocop is clearly buggy....

**Pull request closed without merging**
